ui <- fluidPage(
  titlePanel("HTA2.0 Transcript cluster annotation , "),
  p("by",a("Roman Tremmel",href="mailto:roman.tremmel@ikp-stuttgart.de&subject=PGxLIMS")),
  br(),
  selectizeInput("id", "Select transcript cluster id", choices = NULL, multiple = T),
  hr(),
  h3("Annotation genes"),
  hr(),
  dataTableOutput("DTS_probe_gene"),
  hr(),
  h3("Annotation mRNA"),
  hr(),
  dataTableOutput("DTS_probe_mRNA"),
  hr(),
  h3("Comprehensive information across all annotation files according", 
  a("http://www.affymetrix.com/support/technical/byproduct.affx?product=human_transcriptome")),
  hr(),
  dataTableOutput("DTS_probe_across_releases"),
  hr(),
  p("Built with",
    img(src = "https://www.rstudio.com/wp-content/uploads/2014/04/shiny.png", height = "20px"),
    "by",
    img(src = "https://www.rstudio.com/wp-content/uploads/2014/07/RStudio-Logo-Blue-Gray.png", height = "20px"))
)